{
 "title": "My dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"nodeexporter\"})"
    },
    {
     "expr": "avg(node_load5{job=\"nodeexporter\"})"
    },
    {
     "expr": "avg(node_load15{job=\"nodeexporter\"})"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "Filesystem available bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes" }
   ]
  }
 ]
}